// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnryzlkassiijylndqdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucnl6bGthc3NpaWp5bG5kcWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzI4OTIsImV4cCI6MjA3MzMwODg5Mn0.gEz3MKRqIHNHL1WOI9ZW7QM5IDo9MZS2hyt_jb4Suso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});